services:
  db:
    image: mysql:latest
    container_name: bookingsystem-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-root-pw
      MYSQL_DATABASE: bookingsystem
    volumes:
      - db_data:/var/lib/mysql # Persists db data

volumes:
  db_data:
